name: CI

on: [ push, pull_request ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0

      - name: Install UV and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv==0.5.7
          uv pip install -e '.[test,dev]' --system
          uv pip install pytest-cov --system

      - name: Format code
        run: |
          isort scripts/ tests/
          black scripts/ tests/

      - name: Lint code
        run: |
          bandit -r scripts/ -c pyproject.toml
          ruff check scripts/
          pylint scripts/
          mypy scripts/

      - name: Test code
        run: |
          pytest --cov=scripts --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

